"""refactor_evaluacion_models_gc

Revision ID: 1572279a42df
Revises: 9eb91db28f5a
Create Date: 2026-08-08 01:45:35.627077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1572279a42df'
down_revision: Union[str, None] = '9eb91db28f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_asignatura',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estudiante_seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('asignacion_docente_id', sa.BigInteger(), nullable=True),
    sa.Column('calificacion_final', sa.SmallInteger(), nullable=True),
    sa.Column('situacion_final', postgresql.ENUM('APROBADO', 'EN_COMPLETIVA', 'EN_EXTRAORDINARIA', 'EVALUACION_ESPECIAL', 'PROMOVIDO_CON_CONDICION', 'REPROBADO', 'PENDIENTE', 'RETIRADO', 'TRANSFERIDO', name='situacionfinaltipo', create_type=False), nullable=False),
    sa.Column('nivel_desempeno', postgresql.ENUM('DESTACADO', 'LOGRADO', 'EN_PROCESO', 'INSUFICIENTE', 'SIN_EVALUAR', name='niveldesempenotipo', create_type=False), nullable=False),
    sa.Column('porcentaje_asistencia', sa.SmallInteger(), nullable=True),
    sa.Column('es_borrador', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('calificacion_final BETWEEN 0 AND 100', name='chk_cf'),
    sa.CheckConstraint('porcentaje_asistencia BETWEEN 0 AND 100', name='chk_porcentaje_asistencia'),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignacion_docente_id'], ['asignacion_docente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_seccion_id'], ['estudiante_seccion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_seccion_id', 'asignatura_id', 'anio_escolar_id', name='uq_calificacion_asignatura')
    )
    op.create_index(op.f('ix_calificacion_asignatura_id'), 'calificacion_asignatura', ['id'], unique=False)
    op.create_table('calificacion_grupo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calificacion_asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_competencia_id', sa.BigInteger(), nullable=False),
    sa.Column('nota_p1', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp1', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p2', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp2', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p3', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp3', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p4', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp4', sa.SmallInteger(), nullable=True),
    sa.Column('promedio_competencia', sa.SmallInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('nota_p1 BETWEEN 0 AND 100', name='chk_nota_p1'),
    sa.CheckConstraint('nota_p2 BETWEEN 0 AND 100', name='chk_nota_p2'),
    sa.CheckConstraint('nota_p3 BETWEEN 0 AND 100', name='chk_nota_p3'),
    sa.CheckConstraint('nota_p4 BETWEEN 0 AND 100', name='chk_nota_p4'),
    sa.CheckConstraint('nota_rp1 BETWEEN 0 AND 100 AND (nota_rp1 >= nota_p1)', name='chk_nota_rp1'),
    sa.CheckConstraint('nota_rp2 BETWEEN 0 AND 100 AND (nota_rp2 >= nota_p2)', name='chk_nota_rp2'),
    sa.CheckConstraint('nota_rp3 BETWEEN 0 AND 100 AND (nota_rp3 >= nota_p3)', name='chk_nota_rp3'),
    sa.CheckConstraint('nota_rp4 BETWEEN 0 AND 100 AND (nota_rp4 >= nota_p4)', name='chk_nota_rp4'),
    sa.ForeignKeyConstraint(['calificacion_asignatura_id'], ['calificacion_asignatura.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_competencia_id'], ['grupo_competencia.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion_asignatura_id', 'grupo_competencia_id', name='uq_calificacion_grupo')
    )
    op.create_index(op.f('ix_calificacion_grupo_id'), 'calificacion_grupo', ['id'], unique=False)
    op.add_column('auditoria_calificacion', sa.Column('calificacion_asignatura_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('auditoria_calificacion_calificacion_periodo_id_fkey', 'auditoria_calificacion', type_='foreignkey')
    op.create_foreign_key(None, 'auditoria_calificacion', 'calificacion_asignatura', ['calificacion_asignatura_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('auditoria_calificacion', 'calificacion_periodo_id')
    op.add_column('observacion_boletin', sa.Column('calificacion_asignatura_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('uq_observacion', 'observacion_boletin', type_='unique')
    op.create_unique_constraint('uq_observacion', 'observacion_boletin', ['calificacion_asignatura_id', 'periodo_numero'])
    op.drop_constraint('observacion_boletin_calificacion_periodo_id_fkey', 'observacion_boletin', type_='foreignkey')
    op.create_foreign_key(None, 'observacion_boletin', 'calificacion_asignatura', ['calificacion_asignatura_id'], ['id'], ondelete='CASCADE')
    op.drop_column('observacion_boletin', 'calificacion_periodo_id')
    
    op.drop_index('ix_calificacion_competencia_id', table_name='calificacion_competencia')
    op.drop_table('calificacion_competencia')
    op.drop_index('ix_calificacion_periodo_id', table_name='calificacion_periodo')
    op.drop_table('calificacion_periodo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observacion_boletin', sa.Column('calificacion_periodo_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'observacion_boletin', type_='foreignkey')
    op.create_foreign_key('observacion_boletin_calificacion_periodo_id_fkey', 'observacion_boletin', 'calificacion_periodo', ['calificacion_periodo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_observacion', 'observacion_boletin', type_='unique')
    op.create_unique_constraint('uq_observacion', 'observacion_boletin', ['calificacion_periodo_id', 'periodo_numero'])
    op.drop_column('observacion_boletin', 'calificacion_asignatura_id')
    op.add_column('auditoria_calificacion', sa.Column('calificacion_periodo_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auditoria_calificacion', type_='foreignkey')
    op.create_foreign_key('auditoria_calificacion_calificacion_periodo_id_fkey', 'auditoria_calificacion', 'calificacion_periodo', ['calificacion_periodo_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('auditoria_calificacion', 'calificacion_asignatura_id')
    op.create_table('calificacion_competencia',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('calificacion_periodo_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('competencia_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('periodo_numero', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_recuperacion', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nivel_desempeno', postgresql.ENUM('DESTACADO', 'LOGRADO', 'EN_PROCESO', 'INSUFICIENTE', 'SIN_EVALUAR', name='niveldesempenotipo', create_type=False), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_por', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('periodo_numero >= 1 AND periodo_numero <= 4', name='chk_per_num_comp'),
    sa.ForeignKeyConstraint(['calificacion_periodo_id'], ['calificacion_periodo.id'], name='calificacion_competencia_calificacion_periodo_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencia_especifica.id'], name='calificacion_competencia_competencia_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='calificacion_competencia_pkey'),
    sa.UniqueConstraint('calificacion_periodo_id', 'competencia_id', 'periodo_numero', name='uq_calificacion_competencia')
    )
    op.create_index('ix_calificacion_competencia_id', 'calificacion_competencia', ['id'], unique=False)
    op.create_table('calificacion_periodo',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('estudiante_seccion_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('asignatura_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('anio_escolar_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('asignacion_docente_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nota_p1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_rp1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_p2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_rp2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_p3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_rp3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_p4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_rp4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('calificacion_final', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_completiva', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('calificacion_completiva', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_extraordinaria', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('calificacion_extraordinaria', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nota_especial', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('calificacion_especial', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('situacion_final', postgresql.ENUM('APROBADO', 'EN_COMPLETIVA', 'EN_EXTRAORDINARIA', 'EVALUACION_ESPECIAL', 'PROMOVIDO_CON_CONDICION', 'REPROBADO', 'PENDIENTE', 'RETIRADO', 'TRANSFERIDO', name='situacionfinaltipo', create_type=False), autoincrement=False, nullable=False),
    sa.Column('nivel_desempeno', postgresql.ENUM('DESTACADO', 'LOGRADO', 'EN_PROCESO', 'INSUFICIENTE', 'SIN_EVALUAR', name='niveldesempenotipo', create_type=False), autoincrement=False, nullable=False),
    sa.Column('porcentaje_asistencia', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('es_borrador', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completado_p1', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completado_p2', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completado_p3', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completado_p4', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_por', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('nota_p1 >= 0 AND nota_p1 <= 100', name='chk_nota_p1'),
    sa.CheckConstraint('nota_rp1 >= 0 AND nota_rp1 <= 100 AND nota_rp1 >= nota_p1', name='chk_nota_rp1'),
    sa.CheckConstraint('porcentaje_asistencia >= 0 AND porcentaje_asistencia <= 100', name='chk_porcentaje_asistencia'),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], name='calificacion_periodo_anio_escolar_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignacion_docente_id'], ['asignacion_docente.id'], name='calificacion_periodo_asignacion_docente_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], name='calificacion_periodo_asignatura_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_seccion_id'], ['estudiante_seccion.id'], name='calificacion_periodo_estudiante_seccion_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='calificacion_periodo_pkey'),
    sa.UniqueConstraint('estudiante_seccion_id', 'asignatura_id', 'anio_escolar_id', name='uq_calificacion_periodo')
    )
    op.create_index('ix_calificacion_periodo_id', 'calificacion_periodo', ['id'], unique=False)
    op.drop_index(op.f('ix_calificacion_grupo_id'), table_name='calificacion_grupo')
    op.drop_table('calificacion_grupo')
    op.drop_index(op.f('ix_calificacion_asignatura_id'), table_name='calificacion_asignatura')
    op.drop_table('calificacion_asignatura')
    # ### end Alembic commands ###
