"""add_completiva_extraordinaria_fields

Revision ID: 7cb1db6ba53f
Revises: 1572279a42df
Create Date: 2026-08-10 17:50:51.837738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb1db6ba53f'
down_revision: Union[str, None] = '1572279a42df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion_asignatura', sa.Column('nota_completiva', sa.SmallInteger(), nullable=True))
    op.add_column('calificacion_asignatura', sa.Column('nota_extraordinaria', sa.SmallInteger(), nullable=True))
    op.add_column('calificacion_asignatura', sa.Column('nota_especial', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calificacion_asignatura', 'nota_especial')
    op.drop_column('calificacion_asignatura', 'nota_extraordinaria')
    op.drop_column('calificacion_asignatura', 'nota_completiva')
    # ### end Alembic commands ###
