"""Initial schema

Revision ID: 9eb91db28f5a
Revises: 
Create Date: 2026-08-08 01:27:43.062262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb91db28f5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('abreviatura', sa.String(length=20), nullable=True),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_asignatura_id'), 'asignatura', ['id'], unique=False)
    op.create_table('permiso',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permiso_id'), 'permiso', ['id'], unique=False)
    op.create_table('regional',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_regional_id'), 'regional', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Enum('ADMINISTRADOR', 'DOCENTE', 'COORDINADOR', 'DIRECTOR', name='rolnombretipo'), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('es_superusuario', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('competencia_especifica',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignatura_id', 'codigo', name='uq_competencia_codigo')
    )
    op.create_index(op.f('ix_competencia_especifica_id'), 'competencia_especifica', ['id'], unique=False)
    op.create_table('distrito',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('regional_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_id'], ['regional.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_distrito_id'), 'distrito', ['id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_permiso_id'), 'rol_permiso', ['id'], unique=False)
    op.create_table('centro_educativo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('distrito_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_minerd', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('tanda_principal', sa.Enum('MATUTINA', 'VESPERTINA', 'NOCTURNA', 'SABATINA', name='tandatipo'), nullable=True),
    sa.Column('modalidad', sa.Enum('CIENCIAS_Y_HUMANIDADES', 'TECNICO_PROFESIONAL', 'ARTE', 'ADULTOS', name='modalidadtipo'), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_minerd')
    )
    op.create_index(op.f('ix_centro_educativo_id'), 'centro_educativo', ['id'], unique=False)
    op.create_table('anio_escolar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('centro_id', sa.BigInteger(), nullable=False),
    sa.Column('descripcion', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('CONFIGURACION', 'ACTIVO', 'CERRADO', 'HISTORICO', name='estadoaniotipo'), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name='chk_fechas_anio'),
    sa.ForeignKeyConstraint(['centro_id'], ['centro_educativo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centro_id', 'descripcion', name='uq_anio_centro')
    )
    op.create_index(op.f('ix_anio_escolar_id'), 'anio_escolar', ['id'], unique=False)
    op.create_table('docente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('centro_id', sa.BigInteger(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('primer_nombre', sa.String(length=80), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=80), nullable=True),
    sa.Column('primer_apellido', sa.String(length=80), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=80), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexotipo'), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('titulo_academico', sa.String(length=150), nullable=True),
    sa.Column('especialidad', sa.String(length=150), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centro_educativo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_docente_id'), 'docente', ['id'], unique=False)
    op.create_table('estudiante',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('centro_id', sa.BigInteger(), nullable=False),
    sa.Column('rne', sa.String(length=20), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('libro_acta', sa.String(length=10), nullable=True),
    sa.Column('folio_acta', sa.String(length=10), nullable=True),
    sa.Column('anio_acta', sa.SmallInteger(), nullable=True),
    sa.Column('primer_nombre', sa.String(length=80), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=80), nullable=True),
    sa.Column('primer_apellido', sa.String(length=80), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=80), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexotipo'), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('lugar_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('tiene_condicion_medica', sa.Boolean(), nullable=False),
    sa.Column('condicion_medica', sa.Text(), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centro_educativo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rne', 'centro_id', name='uq_estudiante_rne_centro')
    )
    op.create_index(op.f('ix_estudiante_id'), 'estudiante', ['id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('centro_id', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centro_educativo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_rol_id'), 'usuario_rol', ['id'], unique=False)
    op.create_table('grado',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('ciclo', sa.SmallInteger(), nullable=False),
    sa.Column('modalidad', sa.Enum('CIENCIAS_Y_HUMANIDADES', 'TECNICO_PROFESIONAL', 'ARTE', 'ADULTOS', name='modalidadtipo'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ciclo IN (1, 2)', name='chk_ciclo_grado'),
    sa.CheckConstraint('numero BETWEEN 1 AND 6', name='chk_numero_grado'),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio_escolar_id', 'numero', 'modalidad', name='uq_grado_anio')
    )
    op.create_index(op.f('ix_grado_id'), 'grado', ['id'], unique=False)
    op.create_table('periodo_academico',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVO', 'CERRADO', name='estadoperiodotipo'), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_por', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name='chk_fechas_periodo'),
    sa.CheckConstraint('numero BETWEEN 1 AND 4', name='chk_numero_periodo'),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio_escolar_id', 'numero', name='uq_periodo_anio')
    )
    op.create_index(op.f('ix_periodo_academico_id'), 'periodo_academico', ['id'], unique=False)
    op.create_table('representante',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estudiante_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.Enum('PADRE', 'MADRE', 'TUTOR', 'OTRO', name='tiporepresentantetipo'), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('telefono_1', sa.String(length=20), nullable=True),
    sa.Column('telefono_2', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('es_contacto_emergencia', sa.Boolean(), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representante_id'), 'representante', ['id'], unique=False)
    op.create_table('grado_asignatura',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grado_id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('creditos', sa.SmallInteger(), nullable=True),
    sa.Column('horas_semana', sa.SmallInteger(), nullable=True),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grado_id', 'asignatura_id', name='uq_grado_asig')
    )
    op.create_index(op.f('ix_grado_asignatura_id'), 'grado_asignatura', ['id'], unique=False)
    op.create_table('grupo_competencia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('grado_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_competencia_id'), 'grupo_competencia', ['id'], unique=False)
    op.create_table('seccion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grado_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=False),
    sa.Column('tanda', sa.Enum('MATUTINA', 'VESPERTINA', 'NOCTURNA', 'SABATINA', name='tandatipo'), nullable=False),
    sa.Column('capacidad_max', sa.SmallInteger(), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_id'), 'seccion', ['id'], unique=False)
    op.create_table('asignacion_docente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('docente_id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion_id', 'asignatura_id', 'anio_escolar_id', name='uq_asignacion')
    )
    op.create_index(op.f('ix_asignacion_docente_id'), 'asignacion_docente', ['id'], unique=False)
    op.create_table('estudiante_seccion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estudiante_id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_orden', sa.SmallInteger(), nullable=False),
    sa.Column('condicion_inicial', sa.Enum('PROMOVIDO', 'REPITENTE', 'REINGRESO', 'APLAZADO', 'NUEVO_INGRESO', name='condicioninicialtipo'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'RETIRADO', 'TRANSFERIDO', 'FALLECIDO', name='estadoestudiantetipo'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('motivo_retiro', sa.Text(), nullable=True),
    sa.Column('centro_destino', sa.String(length=200), nullable=True),
    sa.Column('situacion_final', sa.Enum('APROBADO', 'EN_COMPLETIVA', 'EN_EXTRAORDINARIA', 'EVALUACION_ESPECIAL', 'PROMOVIDO_CON_CONDICION', 'REPROBADO', 'PENDIENTE', 'RETIRADO', 'TRANSFERIDO', name='situacionfinaltipo'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'anio_escolar_id', name='uq_estudiante_anio')
    )
    op.create_index(op.f('ix_estudiante_seccion_id'), 'estudiante_seccion', ['id'], unique=False)
    op.create_table('grupo_competencia_detalle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_competencia_id', sa.BigInteger(), nullable=False),
    sa.Column('competencia_id', sa.BigInteger(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencia_especifica.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grupo_competencia_id'], ['grupo_competencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_competencia_id', 'competencia_id', name='uq_grupo_competencia')
    )
    op.create_index(op.f('ix_grupo_competencia_detalle_id'), 'grupo_competencia_detalle', ['id'], unique=False)
    op.create_table('boletin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estudiante_seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo_numero', sa.SmallInteger(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generado_por', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_seccion_id'], ['estudiante_seccion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletin_id'), 'boletin', ['id'], unique=False)
    op.create_table('calificacion_periodo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estudiante_seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('asignatura_id', sa.BigInteger(), nullable=False),
    sa.Column('anio_escolar_id', sa.BigInteger(), nullable=False),
    sa.Column('asignacion_docente_id', sa.BigInteger(), nullable=True),
    sa.Column('nota_p1', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp1', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p2', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp2', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p3', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp3', sa.SmallInteger(), nullable=True),
    sa.Column('nota_p4', sa.SmallInteger(), nullable=True),
    sa.Column('nota_rp4', sa.SmallInteger(), nullable=True),
    sa.Column('calificacion_final', sa.SmallInteger(), nullable=True),
    sa.Column('nota_completiva', sa.SmallInteger(), nullable=True),
    sa.Column('calificacion_completiva', sa.SmallInteger(), nullable=True),
    sa.Column('nota_extraordinaria', sa.SmallInteger(), nullable=True),
    sa.Column('calificacion_extraordinaria', sa.SmallInteger(), nullable=True),
    sa.Column('nota_especial', sa.SmallInteger(), nullable=True),
    sa.Column('calificacion_especial', sa.SmallInteger(), nullable=True),
    sa.Column('situacion_final', sa.Enum('APROBADO', 'EN_COMPLETIVA', 'EN_EXTRAORDINARIA', 'EVALUACION_ESPECIAL', 'PROMOVIDO_CON_CONDICION', 'REPROBADO', 'PENDIENTE', 'RETIRADO', 'TRANSFERIDO', name='situacionfinaltipo'), nullable=False),
    sa.Column('nivel_desempeno', sa.Enum('DESTACADO', 'LOGRADO', 'EN_PROCESO', 'INSUFICIENTE', 'SIN_EVALUAR', name='niveldesempenotipo'), nullable=False),
    sa.Column('porcentaje_asistencia', sa.SmallInteger(), nullable=True),
    sa.Column('es_borrador', sa.Boolean(), nullable=False),
    sa.Column('completado_p1', sa.Boolean(), nullable=False),
    sa.Column('completado_p2', sa.Boolean(), nullable=False),
    sa.Column('completado_p3', sa.Boolean(), nullable=False),
    sa.Column('completado_p4', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('nota_p1 BETWEEN 0 AND 100', name='chk_nota_p1'),
    sa.CheckConstraint('nota_rp1 BETWEEN 0 AND 100 AND (nota_rp1 >= nota_p1)', name='chk_nota_rp1'),
    sa.CheckConstraint('porcentaje_asistencia BETWEEN 0 AND 100', name='chk_porcentaje_asistencia'),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anio_escolar.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignacion_docente_id'], ['asignacion_docente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_seccion_id'], ['estudiante_seccion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_seccion_id', 'asignatura_id', 'anio_escolar_id', name='uq_calificacion_periodo')
    )
    op.create_index(op.f('ix_calificacion_periodo_id'), 'calificacion_periodo', ['id'], unique=False)
    op.create_table('auditoria_calificacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calificacion_periodo_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('campo_modificado', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.String(length=100), nullable=True),
    sa.Column('valor_nuevo', sa.String(length=100), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['calificacion_periodo_id'], ['calificacion_periodo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_calificacion_id'), 'auditoria_calificacion', ['id'], unique=False)
    op.create_table('calificacion_competencia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calificacion_periodo_id', sa.BigInteger(), nullable=False),
    sa.Column('competencia_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo_numero', sa.SmallInteger(), nullable=False),
    sa.Column('nota', sa.SmallInteger(), nullable=True),
    sa.Column('nota_recuperacion', sa.SmallInteger(), nullable=True),
    sa.Column('nivel_desempeno', sa.Enum('DESTACADO', 'LOGRADO', 'EN_PROCESO', 'INSUFICIENTE', 'SIN_EVALUAR', name='niveldesempenotipo'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('periodo_numero BETWEEN 1 AND 4', name='chk_per_num_comp'),
    sa.ForeignKeyConstraint(['calificacion_periodo_id'], ['calificacion_periodo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencia_especifica.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion_periodo_id', 'competencia_id', 'periodo_numero', name='uq_calificacion_competencia')
    )
    op.create_index(op.f('ix_calificacion_competencia_id'), 'calificacion_competencia', ['id'], unique=False)
    op.create_table('observacion_boletin',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calificacion_periodo_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo_numero', sa.SmallInteger(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calificacion_periodo_id'], ['calificacion_periodo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion_periodo_id', 'periodo_numero', name='uq_observacion')
    )
    op.create_index(op.f('ix_observacion_boletin_id'), 'observacion_boletin', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observacion_boletin_id'), table_name='observacion_boletin')
    op.drop_table('observacion_boletin')
    op.drop_index(op.f('ix_calificacion_competencia_id'), table_name='calificacion_competencia')
    op.drop_table('calificacion_competencia')
    op.drop_index(op.f('ix_auditoria_calificacion_id'), table_name='auditoria_calificacion')
    op.drop_table('auditoria_calificacion')
    op.drop_index(op.f('ix_calificacion_periodo_id'), table_name='calificacion_periodo')
    op.drop_table('calificacion_periodo')
    op.drop_index(op.f('ix_boletin_id'), table_name='boletin')
    op.drop_table('boletin')
    op.drop_index(op.f('ix_grupo_competencia_detalle_id'), table_name='grupo_competencia_detalle')
    op.drop_table('grupo_competencia_detalle')
    op.drop_index(op.f('ix_estudiante_seccion_id'), table_name='estudiante_seccion')
    op.drop_table('estudiante_seccion')
    op.drop_index(op.f('ix_asignacion_docente_id'), table_name='asignacion_docente')
    op.drop_table('asignacion_docente')
    op.drop_index(op.f('ix_seccion_id'), table_name='seccion')
    op.drop_table('seccion')
    op.drop_index(op.f('ix_grupo_competencia_id'), table_name='grupo_competencia')
    op.drop_table('grupo_competencia')
    op.drop_index(op.f('ix_grado_asignatura_id'), table_name='grado_asignatura')
    op.drop_table('grado_asignatura')
    op.drop_index(op.f('ix_representante_id'), table_name='representante')
    op.drop_table('representante')
    op.drop_index(op.f('ix_periodo_academico_id'), table_name='periodo_academico')
    op.drop_table('periodo_academico')
    op.drop_index(op.f('ix_grado_id'), table_name='grado')
    op.drop_table('grado')
    op.drop_index(op.f('ix_usuario_rol_id'), table_name='usuario_rol')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_estudiante_id'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_docente_id'), table_name='docente')
    op.drop_table('docente')
    op.drop_index(op.f('ix_anio_escolar_id'), table_name='anio_escolar')
    op.drop_table('anio_escolar')
    op.drop_index(op.f('ix_centro_educativo_id'), table_name='centro_educativo')
    op.drop_table('centro_educativo')
    op.drop_index(op.f('ix_rol_permiso_id'), table_name='rol_permiso')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_distrito_id'), table_name='distrito')
    op.drop_table('distrito')
    op.drop_index(op.f('ix_competencia_especifica_id'), table_name='competencia_especifica')
    op.drop_table('competencia_especifica')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_regional_id'), table_name='regional')
    op.drop_table('regional')
    op.drop_index(op.f('ix_permiso_id'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_asignatura_id'), table_name='asignatura')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
