"""Add peso_porcentaje to GrupoCompetencia

Revision ID: b3764423c9bf
Revises: 7cb1db6ba53f
Create Date: 2026-08-13 11:07:32.082518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3764423c9bf'
down_revision: Union[str, None] = '7cb1db6ba53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calificacion_grupo', 'promedio_competencia',
               existing_type=sa.SMALLINT(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=True)
    op.add_column('grupo_competencia', sa.Column('peso_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupo_competencia', 'peso_porcentaje')
    op.alter_column('calificacion_grupo', 'promedio_competencia',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
